import { Component } from '@angular/core';
import { PeriodicElement, hangmuc } from 'src/app/Interface/PeriodicElement';

const ELEMENT_DATA: hangmuc[] = [
  { ma: 1, ten: 'Bảo trì Hệ thống chụp X-quang KTS ', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 2, ten: 'Bảo trì Hệ thống chụp cắt lớp vi tính CT Scan 128 lát ', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 3, ten: 'Bảo trì Máy siêu âm tổng quát', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 4, ten: 'Bảo trì Máy siêu âm tim', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 5, ten: 'Bảo trì Hệ thống lọc nước RO dùng cho chạy thận nhân tạo', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 6, ten: 'Bảo trì Máy chạy thận nhân tạo kèm máy lọc nước RO mini', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 7, ten: 'Bảo trì Máy gây mê kèm monitor gây mê', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 8, ten: 'Bảo trì Hệ thống chụp cộng hưởng từ MRI 1.5T', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 9, ten: 'Bảo trì Máy hấp tiệt trùng nhiệt độ cao', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 10, ten: 'Bảo trì Bàn mổ hybrid', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 11, ten: 'Bảo trì Hệ thống chụp C-arm', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 12, ten: 'Bảo trì Máy lọc máu liên tục', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 13, ten: 'Bảo trì Hệ thống chụp mạch số hoá xoá nền DSA', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 14, ten: 'Bảo trì Hệ thống nội soi tiêu hoá và mật tuỵ ngược dòng', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 15, ten: 'Bảo trì Máy lọc máu thay huyết tương', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 16, ten: 'Bảo trì Hệ thống rửa quả lọc thận nhân tạo', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 17, ten: 'Bảo trì Hệ thống tim phổi màng ngoài cơ thể ECMO', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 18, ten: 'Bảo trì Hệ thống tim phổi nhân tạo kèm trao đổi nhiệt', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 19, ten: 'Bảo trì Máy bơm bóng đối xung động mạch', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 20, ten: 'Bảo trì Máy thở chức năng cao', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 21, ten: 'Bảo trì Máy cắt đốt điện cao tần', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 22, ten: 'Bảo trì Bơm truyền dịch', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 23, ten: 'Bảo trì Bơm tiêm điện', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 24, ten: 'Bảo trì Máy ECMO', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 25, ten: 'Bảo trì Máy bơm bóng đối xung động mạch', loai: 'Chi phí bảo trì TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 26, ten: 'Kiểm định cân sức khoẻ', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 27, ten: 'Kiểm định huyết áp cơ', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 28, ten: 'Kiểm định nhiệt kế điện tử (đo trán)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 29, ten: 'Kiểm định huyết áp kế điện tử', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 30, ten: 'Kiểm định máy đo điện tim', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 31, ten: 'Kiểm định máy ly tâm', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 32, ten: 'Kiểm định tủ an toàn sinh học cấp ii', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 33, ten: 'Kiểm định tủ cấy vi sinh', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 34, ten: 'Kiểm định micro pipette', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 35, ten: 'Kiểm định máy hấp xử lý mẫu bệnh phẩm', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 36, ten: 'Kiểm định máy xét nghiệm realtime - pcr', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 37, ten: 'Kiểm định nhiệt ẩm kế ', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 38, ten: 'Kiểm định tủ lạnh trữ mẫu', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 39, ten: 'Kiểm định tủ lạnh âm sâu (- 30 °c)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 40, ten: 'Kiểm định tủ lạnh âm sâu (- 70 °c)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 41, ten: 'Kiểm định nhiệt kế thuỷ ngân', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 42, ten: 'Kiểm định máy đo nồng độ cồn', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 43, ten: 'Kiểm định máy đo độ khúc xạ', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 44, ten: 'Kiểm định máy gây mê', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 45, ten: 'Kiểm định máy giúp thở', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 46, ten: 'Kiểm định máy cắt đốt điện cao tần', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 47, ten: 'Kiểm định máy đo tổng chất rắn hòa tan trong nước - thận nhân tạo', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 48, ten: 'Kiểm định nguồn nước ro dùng cho chạy thận nhân tạo cấp cứu', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 49, ten: 'Kiểm định nguồn nước ro dùng cho chạy thận nhân tạo (đơn vị thận nhân tạo)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 50, ten: 'Kiểm định nguồn nước ro dùng cho máy xét nghiệm sinh hóa khoa xn', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 51, ten: 'Kiểm định máy hấp tiệt trùng nhiệt độ cao (ksnk)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 52, ten: 'Kiểm định máy hấp tiệt trùng nhiệt độ cao (<50 lít)', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 53, ten: 'Kiểm định máy đo điện não', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 54, ten: 'Kiểm định máy khử rung tim', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 55, ten: 'Kiểm định máy thận nhân tạo', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 56, ten: 'Kiểm định chi phí kiểm định/hiệu chuẩn tại bệnh viện', loai: 'Chi phí kiểm định, hiệu chuẩn TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 57, ten: 'Sửa chữa Van thở ra máy thở chức năng cao', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 58, ten: 'Sửa chữa Cảm biến lưu lượng thở ra máy thở chức năng cao', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 59, ten: 'Sửa chữa Cảm biến nồng độ oxy máy thở chức năng cao', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 60, ten: 'Sửa chữa Cảm biến lưu lượng thở ra máy gây mê ', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 61, ten: 'Sửa chữa Cảm biến đo SpO2 cho monitor', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 62, ten: 'Sửa chữa Cáp nối cảm biến SpO2 monitor', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 63, ten: 'Sửa chữa Cáp đo điện tim Monitor', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 64, ten: 'Sửa chữa Bao đo huyết áp NIBP cho monitor', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 65, ten: 'Sửa chữa Bánh xe cho giường bệnh, cáng đẩy', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 66, ten: 'Sửa chữa Bộ nguồn bơm tiêm điện, bơm truyền dịch', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 67, ten: 'Sửa chữa Cảm biến đếm giọt máy truyền dịch', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 68, ten: 'Sửa chữa Thanh đốt máy hấp tiệt trùng nhiệt độ cao, máy rửa', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 69, ten: 'Sửa chữa Sửa chữa tay dao 36 kHz mổ não máy cắt đốt siêu âm Cusa Excel+', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 70, ten: 'Sửa chữa Chi phí vật tư thay thế, sửa chữa máy bơm khí Heli của máy MRI - định kỳ', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 71, ten: 'Sửa chữa Bóng đèn Xenon hệ thống kính hiển vi phẫu thuật', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 72, ten: 'Sửa chữa Bóng đèn LED của nguồn sáng nội soi: 3 hệ thống phẩu thuật, 2 hệ thống chẩn đoán', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 73, ten: 'Sửa chữa Dịch vụ kiểm tra sự cố hệ thống CĐHA Siemens Healthineers: CT, DSA, MRI', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 74, ten: 'Sửa chữa Pin (lithium) cho thiết bị: Sốc tim, Điện tim, máy thở, máy mê, bàn mổ, máy thận', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 75, ten: 'Sửa chữa Sửa chữa dụng cụ phẫu thuật hư hỏngc của bộ: trung phẩu, đại phẩu, thần kinh, niệu…...', loai: 'Chi phí sửa chữa TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 76, ten: 'Mua sắm Mũi khoan tự dừng (sử dụng nhiều lần)', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 77, ten: 'Mua sắm Bộ kê tư thế phẫu thuật thần kinh cột sống', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 78, ten: 'Mua sắm Máy làm ấm máu và dịch truyền', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 79, ten: 'Mua sắm Máy Leigasure độc lập ', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 80, ten: 'Mua sắm Máy lọc máu liên tục Prismax', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 81, ten: 'Mua sắm Máy làm ấm máu và dịch truyền', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 82, ten: 'Mua sắm Máy nén ép trị liệu (áp lực hơi)', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 83, ten: 'Mua sắm Bộ máy tập PHCN tay', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 84, ten: 'Mua sắm Máy điện trị liệu 4 kênh phối hợp siêu âm', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 85, ten: 'Mua sắm Máy điều trị chứng khó nuốt', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 86, ten: 'Mua sắm Đo loãng xương', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 87, ten: 'Mua sắm Khoan sọ não', loai: 'Chi phí mua sắm TBYT', phong: 'Phòng trang thiết bị y tế' },
  { ma: 88, ten: 'Mua sắm Banh mũi loại sử dụng nhiều lần', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 89, ten: 'Mua sắm Kẹp lưỡng cực (phẫu thuật thần kinh)', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 90, ten: 'Mua sắm Gối kê đầu bệnh nhân ', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 91, ten: 'Mua sắm Cây treo dịch truyền di động', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 92, ten: 'Mua sắm Cây treo dịch truyền di động', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 93, ten: 'Mua sắm Cây treo dịch truyền di động', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 94, ten: 'Mua sắm Ghế chờ thân nhân', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 95, ten: 'Mua sắm Máy phun khí dung', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng trang thiết bị y tế' },
  { ma: 96, ten: 'Bảo trì bảo dưỡng hệ thống vận chuyển mẫu (pts)', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 97, ten: 'Bảo trì hệ thống ups (gói cơ bản)', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 98, ten: 'Bảo trì máy phát điện 2015kva', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 99, ten: 'Kiểm định trạm biến áp', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 100, ten: 'Bảo trì đo chống sét, tiếp địa, cách âm', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 101, ten: 'Bảo trì thiết bị đóng cắt', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 102, ten: 'Bảo trì hệ thống bơm', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 103, ten: 'Bảo trì hệ thống chiller', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 104, ten: 'Bảo trì định kỳ hệ thống thang máy', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 105, ten: 'Bảo trì hệ thống gas, khí đốt ', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 106, ten: 'Bảo trì kiểm định bình tích áp + đồng hồ+ valve', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 107, ten: 'Bảo trì bồn chứa', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 108, ten: 'Bảo trì hệ thống camera', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 109, ten: 'Bảo trì hệ thống gọi y tá', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 110, ten: 'Bảo trì và xử lý sự cố pccc ', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 111, ten: 'Bảo trì ht khí oxy trung tâm', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 112, ten: 'Bảo trì kiểm tra xử lý sự cố hc cctv', loai: 'Chi phí bảo trì TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 113, ten: 'Sửa chữa  cửa ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 114, ten: 'Sửa chữa  sơn ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 115, ten: 'Sửa chữa  gạch ốp lát và đá (ban công trồng rau) ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 116, ten: 'Sửa chữa  khóa ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 117, ten: 'Sửa chữa  trần thạch cao và vách ngăn (dự trù chống nứt, kháng khuẩn) ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 118, ten: 'Sửa chữa  kính và vách kính, inox ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 119, ten: 'Sửa chữa  sàn vinyl và thảm lót ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 120, ten: 'Sửa chữa  sàn gỗ và giấy dán tường, rèm  ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 121, ten: 'Sửa chữa  chống thấm và cải tạo, sửa chửa xd ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 122, ten: 'Sửa chữa  hệ thống điện ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 123, ten: 'Sửa chữa  hệ thống cấp thoát nước (nước sinh hoạt) ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 124, ten: 'Sửa chữa  ht phòng cháy chữa cháy ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 125, ten: 'Sửa chữa  ht điều hòa không khí và thông gió ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 126, ten: 'Sửa chữa  ht cctv ', loai: 'Chi phí sửa chữa TSCĐ', phong: 'Phòng quản lý hạ tầng' },
  { ma: 127, ten: 'Dịch vụ dịch vụ vệ sinh ', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 128, ten: 'Dịch vụ dịch vụ bảo vệ', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 129, ten: 'Dịch vụ dịch vụ quản lý bãi xe', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 130, ten: 'Dịch vụ dv chăm sóc cây xanh', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 131, ten: 'Dịch vụ kiểm soát dịch hại', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 132, ten: 'Dịch vụ hợp đồng vận hành htxlnt', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 133, ten: 'Dịch vụ hợp đồng quan trắc môi trường', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 134, ten: 'Dịch vụ hợp đồng đo liều bức xạ cá nhân', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 135, ten: 'Dịch vụ hợp đồng kiểm định và gia hạn giấy phép an toàn bức xạ', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 136, ten: 'Dịch vụ thu gom chất thải rắn thông thường', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 137, ten: 'Dịch vụ thu gom chất thải rắn nguy hại', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 138, ten: 'Dịch vụ hợp đồng thuê 2 container khu sàn lọc', loai: 'Chi phí hoạt động hằng ngày', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 139, ten: 'Bảo hiểm trách nhiệm công cộng', loai: 'Chi phí quản lý môi trường', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 140, ten: 'Bảo hiểm cháy nổ', loai: 'Chi phí bảo hiểm', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 141, ten: 'hoàn tất nội thất lầu 6 cánh trái (25 giường còn lại)', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 142, ten: 'đầu tư thêm ghế chờ khu vực ksk cho bệnh nhân', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 143, ten: 'trang bị rèm cửa sổ khu vực lầu 8  (tránh  nắng làm hư sàn)', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 144, ten: 'cải tạo khu vực kiểm đồ vải dơ', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 145, ten: 'cải tạo phòng làm việc trang thiết bị y tế', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' },
  { ma: 146, ten: 'cải tạo phòng thay đồ khu vực chẩn đoán hình ảnh đúng qui định (paitent privacy)', loai: 'Chi phí mua sắm TSCĐ', phong: 'Phòng hỗ trợ vận hành' }
]


@Component({
  selector: 'app-hangmuc',
  templateUrl: './hangmuc.component.html',
  styleUrls: ['./hangmuc.component.scss']
})
export class HangmucComponent {
  displayedColumns: string[] = ['ma', 'ten', 'loai', 'phong'];
  dataSource = ELEMENT_DATA;
}

